### ISSUE TITLE
[Help Wanted] Translations & Localizations

### ISSUE THREAD

**Issue by SmithsonianDSP** [SmithsonianDSP/QuickVideoInfo#9]
I have extracted the majority of the strings from the code and, with the help of Azure and MyMemory's translation APIs, have produced initial translations for the following languages. 

---

### Current translations that need to be reviewed/proofed:

These all probably need to be double-checked against the [original English strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values/Strings.xml).

- [ ] Arabic - [strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values-ar/strings.xml)

- [ ] German - [strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values-de/strings.xml) 

- [ ] Spanish - [strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values-es/strings.xml)

- [ ] French - [strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values-fr/strings.xml)

- [ ] Hindi - [strings.xml](https://github.com/SmithsonianDSP/QuickVideoInfo/blob/master/YTII.Android.App/Resources/values-hi/strings.xml)

---

### Other languages still likely desired:

- [ ] Portuguese 

- [ ] Russian

- [ ] Italian

- [ ] **Any/all other languages!**  
  
  If you'd like to see localizations for a language not already listed above, please let me know and I will add it to the list!

---

**If you would like to help with the translations/localizations, either by improving the current/machine-translated versions or by adding another language not listed, please don't hesitate to contact me or make a Pull Request!**

**Comment by srishag** [comment]
Is this project active? Spotted some errors in Hindi translation, I can help!

**Comment by SmithsonianDSP** [comment]
Well, I haven't really seen much need to continue development since @talklittle added inline YouTube playback to _reddit is fun_, which was the original inspiration for the app... so, apart from fixing bugs or any breaking changes with the APIs, I wasn't really planning on making any changes, really...

But you're more than welcome to fork the `strings.xml` in the [corresponding `values` folder](https://github.com/SmithsonianDSP/QuickVideoInfo/tree/master/YTII.Android.App/Resources) (which, for Hindi, would be `values-hi`), make the corrections, and then submit a pull request! 

If you do, then I'll merge the changes and put out an app update shortly afterwards.

**Comment by MatheusNtg** [comment]
I would like to contribute translating to Portuguese, can I do this and submit a pull request ?

**Comment by SmithsonianDSP** [comment]
> I would like to contribute translating to Portuguese, can I do this and submit a pull request ?

Sure; as I mentioned in a [previous comment](https://github.com/SmithsonianDSP/QuickVideoInfo/issues/9#issuecomment-326619533), this project is no longer in active development but if you make a PR with the localization values, I'll merge it.
